Fix 3852:  …
bcgov/fams3 pull request #561
Opened 2021-11-19 22:36 UTC by KyleKayfish

# Description

This PR includes the following proposed change(s):

Added a filter to not retry CSNO on deep search unless it is a numeric value that was returned

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Existing unit tests only

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [x ] New and existing unit tests pass locally with my changes

2021-11-30 17:54 UTC, NovaVic requested changes
Data type change may be necessary. Please have a look at the additional (in detail) comment near a specific line   in code.

2021-11-30 17:59 UTC, KyleKayfish commented on app/SearchApi/SearchApi.Web/DeepSearch/IdentifierComparer.cs
> +                        if (int.TryParse(item.Value, out n)) {
This is a valid point.  The max is we have now is 9 character which would be less that int max but for future proofing will change this to a long so max value is 19 characters or 9,223,372,036,854,775,807

2021-11-30 18:44 UTC, KyleKayfish commented on app/SearchApi/SearchApi.Web/DeepSearch/IdentifierComparer.cs
> +                        if (int.TryParse(item.Value, out n)) {
updated to use long

2021-12-01 00:41 UTC, NovaVic approved these changes

2021-12-01 17:00 UTC, merged